apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
      matchLabels:
        service: reverse-proxy
  template:
    metadata:
      labels:
        service: reverse-proxy
        version: v2
    spec:
      containers:
      - image: mariam8mohamed/reverse-proxy
        name: reverse-proxy
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds:  5
          periodSeconds: 5
          successThreshold: 1          
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always


